name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.carinfotainment_user }}
          password: ${{ secrets.carinfotainment_token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag my-application

      - name: Run unit tests in Docker container
        run: docker run python3 -m unittest */UnitTests/test_*