name: Unit Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.carinfotainment_user }}
          password: ${{ secrets.carinfotainment_token }}

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --file Dockerfile --tag car_infotainment_image

      - name: Install dependencies
        run: |
            python -m venv venv
            source venv/bin/activate
            pip install --upgrade pip
            pip install -r requirements.txt

      - name: Set PATH environment variable
        run: echo "PATH=$PATH:/app/venv/bin" >> $GITHUB_ENV

      - name: Run unit tests in Docker container
        run: docker run --rm car_infotainment_image sh -c "python -m unittest discover -v"